openapi: 3.1.0
info:
  title: API Planilha ACOPLADO
  description: Retorna os dados da aba "ACOPLADO" de uma planilha do Google Sheets com colunas de A até R.
  version: 1.0.0

servers:
  - url: https://planilha-api.onrender.com

paths:
  /dados-planilha:
    get:
      operationId: getPlanilhaAcoplado
      summary: Retorna os dados da planilha ACOPLADO
      description: Este endpoint retorna um array de arrays com os dados da planilha do Google Sheets (colunas A até R da aba ACOPLADO).
      responses:
        '2041':
          description: Dados retornados com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    type: string
